server:
  port: 8004

scheduler:
  enabled: true
  trigger:
    #    cron-expression: 0 0 18 ? * * *
    cron-expression: 0/30 * * ? * * *
spring:
  batch:
    job:
      enabled: false
  mail:
    host: localhost
    port: 2500
app:
  default-email-sender:
    no-reply@test.com