server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8003/
          predicates:
            - Path=/api/user/**
        - id: librairie
          uri: http://localhost:8001/
          predicates:
            - Path=/api/librairie/**
